#!/bin/bash

ROOT=`pwd`
UBOOT_PATH=uboot
KERNEL_PATH=kernel/common

##########################################################################
# Uboot build
##########################################################################
cd $ROOT/$UBOOT_PATH
if [ ! -f include/config.h ]; then
	echo "Configuring omap3_beagle_config"
	make CROSS_COMPILE=arm-none-linux-gnueabi- omap3_beagle_config
fi
make CROSS_COMPILE=arm-none-linux-gnueabi- 
if [ -f $ROOT/$UBOOT_PATH/u-boot ]; then
	mkdir -p $ROOT/out/boot
	cp $ROOT/$UBOOT_PATH/u-boot $ROOT/out/boot/
fi

##########################################################################
# Kernel build
##########################################################################
cd $ROOT/$KERNEL_PATH
if [ ! -f ./.config ]; then
	echo "Configuring omap3_beagle_defconfig"
	make CROSS_COMPILE=arm-none-linux-gnueabi- ARCH=arm omap3_beagle_defconfig 
fi
make CROSS_COMPILE=arm-none-linux-gnueabi- ARCH=arm uImage
if [ -f $ROOT/$KERNEL_PATH/arch/arm/boot/uImage ]; then
	mkdir -p $ROOT/out/boot
	cp $ROOT/$KERNEL_PATH/arch/arm/boot/uImage $ROOT/out/
fi

##########################################################################
# Prebuilt images
##########################################################################
cd $ROOT/build/boot
make -f Makefile    # build bootcmd
cp -f $ROOT/build/boot/MLO $ROOT/out/boot/
cp -f $ROOT/build/boot/boot.scr $ROOT/out/boot/
cp -f $ROOT/build/boot/u-boot.bin $ROOT/out/boot/

##########################################################################
# User/Applications
##########################################################################
